gms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls') ),
    path('accounts/', include('django.contrib.auth.urls')),
    
    

]

main/urls.py
from django.urls import path, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("services", views.all_services, name="services"),
    path("pagedetail/<int:id>", views.page_detail, name="pagedetail"),
    path("faq", views.faq_list, name="faq"),
    path("contact", views.contact_page, name="contact_page"),
    path("gallery", views.gallery, name="gallery"),
    path("gallerydetail/<int:id>", views.gallery_detail, name="gallery_detail"),
    path("pricing", views.pricing, name="pricing"),
    path("accounts/signup", views.signup, name="signup"),
    path('accounts/password-change', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html', success_url =reverse_lazy("auth_password_done")), name='auth_password_change'),
    path('accounts/password-change/done', auth_views.PasswordChangeDoneView.as_view(template_name='registration/change_done.html'), name='auth_password_done'),
    path("checkout/<int:plan_id>", views.checkout, name="checkout"),
    path(
        "checkout_session/<int:plan_id>",
        views.checkout_session,
        name="checkout_session",
    ),
    path("pay_success", views.pay_success, name="pay_success"),
    path("pay_cancel", views.pay_cancel, name="pay_cancel"),
    # User Dashboard Section start
    path("user_dashboard", views.user_dashboard, name="user_dashboard"),
    path("update_profile", views.update_profile, name="update_profile"),
    # Login
    path("accounts/login/", views.login_view, name='login'),

    # Trainer Login
    path("trainerlogin", views.trainerlogin, name="trainerlogin"),
    path("trainerlogout", views.trainerlogout, name="trainerlogout"),
    path("trainer_dashboard", views.trainer_dashboard, name="trainer_dashboard"),
    path("trainer_profile", views.trainer_profile, name="trainer_profile"),
    path("trainer_subscribers", views.trainer_subscribers, name="trainer_subscribers"),
    path("trainer_payments", views.trainer_payments, name="trainer_payments"),
    path(
        "trainer_changepassword",
        views.trainer_changepassword,
        name="trainer_changepassword",
    ),
    path("trainer_notifs", views.trainer_notifs, name="trainer_notifs"),
    # Notifications
    path("notifs", views.notifs, name="notifs"),
    path("get_notifs", views.get_notifs, name="get_notifs"),
    path("mark_read_notif", views.mark_read_notif, name="mark_read_notif"),
    # Messages
    path("messages", views.trainer_msgs, name="messages"),
    path(
        "mark_read_trainer_notif",
        views.mark_read_trainer_notif,
        name="mark_read_trainer_notif",
    ),
    # Reports
    path("report_for_user", views.report_for_user, name="report_for_user"),
    path("report_for_trainer", views.report_for_trainer, name="report_for_trainer"),
    path("equipments", views.equipment_list, name="equipment_list")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from datetime import timedelta
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
import json

# Create your models here.
# Banners
class Banners(models.Model):
	img=models.ImageField(upload_to="banners/")
	alt_text=models.CharField(max_length=150)

	class Meta:
		verbose_name_plural='Banners'

	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe(f"<img src='{self.img.url}' width='80' />")

# Services to offer
class Service(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="services/",null=True)

	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe(f"<img src='{self.img.url}' width='80' />")

# Pages
class Page(models.Model):
    title = models.CharField(max_length=200)
    detail = models.TextField()
    
    def __str__(self):
        return self.title
    
# FAQ
class Faq(models.Model):
    quest =models.CharField(max_length=200)
    ans = models.TextField()
    
    def __str__(self):
        return self.quest
    

# Enquiry Model
class Enquiry(models.Model):
    full_name=models.CharField(max_length=150)
    email=models.CharField(max_length=150)
    detail=models.TextField()
    send_time=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'enquiries'
    def __str__(self):
        return self.full_name
    
# Gallery Model
class Gallery(models.Model):
    title=models.CharField(max_length=150)
    detail=models.TextField()
    img=models.ImageField(upload_to="gallery/",null=True)
    
    class Meta:
        verbose_name_plural = 'Galleries'

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe(f"<img src='{self.img.url}' width='80' />")
    

# Gallery Images
class GalleryImage(models.Model):
	gallery=models.ForeignKey(Gallery, on_delete=models.CASCADE,null=True)
	alt_text=models.CharField(max_length=150)
	img=models.ImageField(upload_to="gallery_imgs/",null=True)

	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe(f"<img src='{self.img.url}' width='80' />")

# Subscription Plans
class SubPlan(models.Model):
	title=models.CharField(max_length=150)
	price=models.IntegerField()
	max_member=models.IntegerField(null=True)
	highlight_status=models.BooleanField(default=False,null=True)
	validity_days=models.IntegerField(null=True)

	def __str__(self):
		return self.title

# Subscription Plans Features
class SubPlanFeature(models.Model):
	# subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	subplan=models.ManyToManyField(SubPlan)
	title=models.CharField(max_length=150)

	def __str__(self):
		return self.title
    

# Package Discounts
class PlanDiscount(models.Model):
	subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	total_months=models.IntegerField()
	total_discount=models.IntegerField()

	def __str__(self):
		return str(self.total_months)

# Subscriber
class Subscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	mobile=models.CharField(max_length=20)
	address=models.TextField()
	img=models.ImageField(upload_to="subs/",null=True)

	def __str__(self):
		return str(self.user)

	def image_tag(self):
		if self.img:
			return mark_safe(f"<img src='{self.img.url}' width='80' />")
		else:
			return 'no-image'

@receiver(post_save, sender=User)
def create_subscriber(sender, instance, created, **kwrargs):
    if created:
        Subscriber.objects.create(user=instance)

# Subscription
class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    plan = models.ForeignKey('SubPlan', on_delete=models.CASCADE, null=True)
    price = models.CharField(max_length=50)  # Consider using DecimalField for monetary values
    reg_date = models.DateField(auto_now_add=True, null=True)
    # end_date should be automatically calculated based on reg_date and plan validity
    # end_date = models.DateField(null=True, blank=True)  # Remove this field
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        # Deactivate other active subscriptions for the user
        if self.is_active:
            Subscription.objects.filter(user=self.user, is_active=True).exclude(pk=self.pk).update(is_active=False)
        super().save(*args, **kwargs)

    @property
    def end_date(self):
        # Calculate end_date based on reg_date and plan validity_days
        if self.reg_date and self.plan:
            return self.reg_date + timedelta(days=self.plan.validity_days)
        return None

    @property
    def is_expired(self):
        # Check if subscription is expired based on current date and end_date
        return timezone.now().date() > self.end_date if self.end_date else False

    def __str__(self):
        return f"{self.user.username} - {self.plan.title}"

    class Meta:
        verbose_name = "Subscription"
        verbose_name_plural = "Subscriptions"
# Trainer
class Trainer(models.Model):
	full_name=models.CharField(max_length=100)
	username=models.CharField(max_length=100,null=True)
	pwd=models.CharField(max_length=50,null=True)
	mobile=models.CharField(max_length=100)
	address=models.TextField()
	is_active=models.BooleanField(default=False)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers/")
	salary=models.IntegerField(default=0)

	facebook=models.CharField(max_length=200,null=True)
	twitter=models.CharField(max_length=200,null=True)
	pinterest=models.CharField(max_length=200,null=True)
	youtube=models.CharField(max_length=200,null=True)

	def __str__(self):
		return str(self.full_name)

	def image_tag(self):
		if self.img:
			return mark_safe(f"<img src='{self.img.url}' width='80' />")
		else:
			return 'no-image'


# Notifications Json Response Via Ajax
class Notify(models.Model):
	notify_detail=models.TextField()
	read_by_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
	read_by_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,blank=True)

	def __str__(self):
		return str(self.notify_detail)

# Markas Read Notification By User
class NotifUserStatus(models.Model):
	notif=models.ForeignKey(Notify, on_delete=models.CASCADE)
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	status=models.BooleanField(default=False)

	class Meta:
		verbose_name_plural='Notification Status'
  

# Assign Subscriber to Trainer
class AssignSubscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)

	def __str__(self):
		return str(self.user)

# Trainer Achivements
class TrainerAchivement(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	title=models.CharField(max_length=100)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers_achivements/")

	def __str__(self):
		return str(self.title)

	def image_tag(self):
		if self.img:
			return mark_safe(f"<img src='{self.img.url}' width='80' />")
		else:
			return 'no-image'


# TrainerSalary Model
class TrainerSalary(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	amt=models.IntegerField()
	amt_date=models.DateField()
	remarks=models.TextField(blank=True)

	class Meta:
		verbose_name_plural='Trainer Salary'

	def __str__(self):
		return str(self.trainer.full_name)


# Trainer Notifications
class TrainerNotification(models.Model):
	notif_msg=models.TextField()

	def __str__(self):
		return str(self.notif_msg)

	def save(self,*args,**kwargs):
		super(TrainerNotification, self).save(*args,**kwargs)
		channel_layer=get_channel_layer()
		notif=self.notif_msg
		total=TrainerNotification.objects.all().count()
		# total=TrainerNotification.objects.all().filter(notiftrainerstatus__status=True).count()

		async_to_sync(channel_layer.group_send)(
			'noti_group_name',{
				'type':'send_notification',
				'value':json.dumps({'notif':notif,'total':total})
			}
		)

# Markas Read Notification By Trainer
class NotifTrainerStatus(models.Model):
	notif=models.ForeignKey(TrainerNotification, on_delete=models.CASCADE)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	status=models.BooleanField(default=False)

	class Meta:
		verbose_name_plural='Trainer Notification Status'

# SubscriberMsg
class TrainerMsg(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True)
	message=models.TextField()

	class Meta:
		verbose_name_plural='Messages For Trainer'
  
# Reports
class TrainerSubscriberReport(models.Model):
	report_for_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,related_name='report_for_trainer')
	report_for_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name='report_for_user')
	report_from_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,related_name='report_from_trainer',blank=True)
	report_from_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name='report_from_user',blank=True)
	report_msg=models.TextField()
 
 
class AppSetting(models.Model):
	logo_img=models.ImageField(upload_to='app_logos/')

	def image_tag(self):
		if self.logo_img:
			return mark_safe(f"<img src='{self.logo_img.url}' width='80' />")
		else:
			return 'no-image'

from django.db import models

class EquipmentInventory(models.Model):
  STATUS_CHOICES = (
    ('available', 'Available'),
    ('under_maintenance', 'Under Maintenance'),
    ('unavailable', 'Unavailable'),
  )
  name = models.CharField(max_length=255)

main/templates/user/dashboard.html
{% extends "base.html" %}
{% block content %}
    <!-- Main Start -->
    <main>
        <!-- Services -->
        <section class="container my-4">
            <div class="row">
                <div class="col-3">{% include "user/left-sidebar.html" %}</div>
                <div class="col-9">
                    <h3 class="mb-4 border-bottom pb-1">Dashboard</h3>
                    <div class="row">
                        <div class="col-md-6">
                            {% if current_plan %}
                                <div class="card">
                                    <h5 class="card-header">Current Package</h5>
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item">{{ current_plan.plan }}</li>
                                        <li class="list-group-item">Price: {{ current_plan.price }}</li>
                                        <li class="list-group-item">Validity: {{ current_plan.plan.validity_days }} Days</li>
                                        <li class="list-group-item">Purchase Date: {{ current_plan.reg_date }}</li>
                                        <li class="list-group-item">
                                            Expiry Date:
                                            {% if current_subscription.is_expired %}
                                                Your subscription has expired.
                                            {% else %}
                                                {{ enddate }}
                                            {% endif %}
                                        </li>
                                    </ul>
                                </div>
                            {% else %}
                                <div class="card">
                                    <h5 class="card-header">Current Package</h5>
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item text-danger">
                                            <p class="text-danger d-inline">Not Subscribed</p>
                                            &nbsp;|&nbsp;<a href="{% url 'pricing' %}">Subscribe Now</a>
                                        </li>
                                    </ul>
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6">
                            {% if my_trainer %}
                                <div class="card">
                                    <h5 class="card-header">Assigned Trainer</h5>
                                    <img src="{{ my_trainer.trainer.img.url }}"
                                         class="card-img-top"
                                         alt="{{ my_trainer.trainer }}" />
                                    <div class="card-body">
                                        <h6 class="card-text">{{ my_trainer.trainer }}</h6>
                                    </div>
                                    <div class="card-footer">
                                        <a href="{{ my_trainer.trainer.facebook }}" title="Facebook"><i class="bi bi-facebook"></i></a>
                                        <a href="{{ my_trainer.trainer.twitter }}" title="Twitter"><i class="bi bi-twitter"></i></a>
                                        <a href="{{ my_trainer.trainer.youtube }}"><i class="bi bi-youtube" title="YouTube"></i></a>
                                        <a href="{{ my_trainer.trainer.pinterest }}" title="Pinterest">P</a>
                                        <button data-bs-toggle="modal"
                                                data-bs-target="#AchivementModal"
                                                title="Achivement"
                                                class="float-end btn btn-sm btn-success">
                                            <i class="bi bi-trophy-fill"></i>
                                        </button>
                                        <!-- Modal -->
                                        <div class="modal fade"
                                             id="AchivementModal"
                                             tabindex="-1"
                                             aria-labelledby="exampleModalLabel"
                                             aria-hidden="true">
                                            <div class="modal-dialog modal-lg">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">{{ my_trainer.trainer.full_name }} Achivements</h5>
                                                        <button type="button"
                                                                class="btn-close"
                                                                data-bs-dismiss="modal"
                                                                aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <table class="table table-hover">
                                                            <thead>
                                                                <tr>
                                                                    <th>Title</th>
                                                                    <th>Image</th>
                                                                    <th>Detail</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                                {% for achive in my_trainer.trainer.trainerachivement_set.all %}
                                                                    <tr>
                                                                        <td>{{ achive.title }}</td>
                                                                        <td>
                                                                            <img src="{{ achive.img.url }}" width="80" />
                                                                        </td>
                                                                        <td>{{ achive.detail }}</td>
                                                                    </tr>
                                                                {% endfor %}
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% comment %}
							{% else %}
							<div class="card">
								<h5 class="card-header">Assigned Trainer</h5>
								<ul class="list-group list-group-flush">
									<li class="list-group-item text-danger"><p class="text-danger d-inline">Not Subscribed</p>&nbsp;|&nbsp;<a href="{% url 'pricing' %}">Subscribe Now</a></li>
								</ul>
							</div>
                                {% endcomment %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End -->
    </main>
    <!-- End -->
{% endblock content %}

main/templates/user/left-sidebar.html
<div class="list-group">
   <a href="{% url 'user_dashboard' %}"
      class="list-group-item {% if request.path == '/user_dashboard' %}active{% endif %}">Dashboard</a>
   <a href="{% url 'update_profile' %}"
      class="list-group-item {% if request.path == '/update_profile' %}active{% endif %}">Profile</a>
   <a href="{% url 'auth_password_change' %}"
      class="list-group-item {% if request.path == '/accounts/password-change' %}active{% endif %}">Change Passwords</a>
   {% comment %}
    <a href="{% url 'notifs' %}" class="list-group-item {% if request.path == '/notifs' %}active{% endif %}">Notifications <span class="float-end badge bg-info mt-1">{{ total_unread }}</span></a>
	<a href="#" class="list-group-item">Messages</a>
   <a href="{% url 'report_for_trainer' %}"
      class="list-group-item {% if request.path == '/report_for_trainer' %} active {% endif %}">Report for Trainer</a> {% endcomment %}
</div>

main/templates/user/update-profile.html
{% extends "base.html" %}
{% block content %}
    <!-- Main Start -->
    <main>
        <!-- Services -->
        <section class="container my-4">
            <div class="row">
                <div class="col-3">{% include "user/left-sidebar.html" %}</div>
                <div class="col-9">
                    <h3 class="mb-4 border-bottom pb-1">Update Profile</h3>
                    {% if msg %}<p class="text-success">{{ msg }}</p>{% endif %}
                    <form method="post" action="">
                        <table class="table table-bordered">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <tr>
                                <th>{{ form.first_name.label_tag }}</th>
                                <td>{{ form.first_name }}</td>
                            </tr>
                            {% if form.first_name.errors %}
                                <tr>
                                    <td colspan="2" class="alert alert-danger">{{ form.first_name.errors }}</td>
                                </tr>
                            {% endif %}
                            <tr>
                                <th>{{ form.last_name.label_tag }}</th>
                                <td>{{ form.last_name }}</td>
                            </tr>
                            {% if form.last_name.errors %}
                                <tr>
                                    <td colspan="2" class="alert alert-danger">{{ form.last_name.errors }}</td>
                                </tr>
                            {% endif %}
                            <tr>
                                <th>{{ form.email.label_tag }}</th>
                                <td>{{ form.email }}</td>
                            </tr>
                            {% if form.email.errors %}
                                <tr>
                                    <td colspan="2" class="alert alert-danger">{{ form.email.errors }}</td>
                                </tr>
                            {% endif %}
                            <tr>
                                <th>{{ form.username.label_tag }}</th>
                                <td>{{ form.username }}</td>
                            </tr>
                            {% if form.username.errors %}
                                <tr>
                                    <td colspan="2" class="alert alert-danger">{{ form.username.errors }}</td>
                                </tr>
                            {% endif %}
                            <tr>
                                <th>{{ form.phone_number.label_tag }}</th>
                                <td>{{ form.phone_number }}</td>
                            </tr>
                            {% if form.phone_number.errors %}
                                <tr>
                                    <td colspan="2" class="alert alert-danger">{{ form.phone_number.errors }}</td>
                                </tr>
                            {% endif %}
                            <tr>
                                <td colspan="2">
                                    <input type="submit" class="btn btn-primary" />
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </section>
        <!-- End -->
    </main>
    <!-- End -->
{% endblock content %}