gms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls') ),
    path('accounts/', include('django.contrib.auth.urls')),
    
    

]

main/urls.py
from django.urls import path, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("services", views.all_services, name="services"),
    path("pagedetail/<int:id>", views.page_detail, name="pagedetail"),
    path("faq", views.faq_list, name="faq"),
    path("contact", views.contact_page, name="contact_page"),
    path("gallery", views.gallery, name="gallery"),
    path("gallerydetail/<int:id>", views.gallery_detail, name="gallery_detail"),
    path("pricing", views.pricing, name="pricing"),
    path("accounts/signup", views.signup, name="signup"),
    path('accounts/password-change', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html', success_url =reverse_lazy("auth_password_done")), name='auth_password_change'),
    path('accounts/password-change/done', auth_views.PasswordChangeDoneView.as_view(template_name='registration/change_done.html'), name='auth_password_done'),
    path("checkout/<int:plan_id>", views.checkout, name="checkout"),
    path(
        "checkout_session/<int:plan_id>",
        views.checkout_session,
        name="checkout_session",
    ),
    path("pay_success", views.pay_success, name="pay_success"),
    path("pay_cancel", views.pay_cancel, name="pay_cancel"),
    # User Dashboard Section start
    path("user_dashboard", views.user_dashboard, name="user_dashboard"),
    path("update_profile", views.update_profile, name="update_profile"),
    # Login
    path("accounts/login/", views.login_view, name='login'),

    # Trainer Login
    path("trainerlogin", views.trainerlogin, name="trainerlogin"),
    path("trainerlogout", views.trainerlogout, name="trainerlogout"),
    path("trainer_dashboard", views.trainer_dashboard, name="trainer_dashboard"),
    path("trainer_profile", views.trainer_profile, name="trainer_profile"),
    path("trainer_subscribers", views.trainer_subscribers, name="trainer_subscribers"),
    path("trainer_payments", views.trainer_payments, name="trainer_payments"),
    path(
        "trainer_changepassword",
        views.trainer_changepassword,
        name="trainer_changepassword",
    ),
    path("trainer_notifs", views.trainer_notifs, name="trainer_notifs"),
    # Notifications
    path("notifs", views.notifs, name="notifs"),
    path("get_notifs", views.get_notifs, name="get_notifs"),
    path("mark_read_notif", views.mark_read_notif, name="mark_read_notif"),
    # Messages
    path("messages", views.trainer_msgs, name="messages"),
    path(
        "mark_read_trainer_notif",
        views.mark_read_trainer_notif,
        name="mark_read_trainer_notif",
    ),
    # Reports
    path("report_for_user", views.report_for_user, name="report_for_user"),
    path("report_for_trainer", views.report_for_trainer, name="report_for_trainer"),
    path("equipments", views.equipment_list, name="equipment_list")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from datetime import timedelta
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
import json

# Create your models here.
# Banners
class Banners(models.Model):
	img=models.ImageField(upload_to="banners/")
	alt_text=models.CharField(max_length=150)

	class Meta:
		verbose_name_plural='Banners'

	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe(f"<img src='{self.img.url}' width='80' />")

# Services to offer
class Service(models.Model):
	title=models.CharField(max_length=150)
	detail=models.TextField()
	img=models.ImageField(upload_to="services/",null=True)

	def __str__(self):
		return self.title

	def image_tag(self):
		return mark_safe(f"<img src='{self.img.url}' width='80' />")

# Pages
class Page(models.Model):
    title = models.CharField(max_length=200)
    detail = models.TextField()
    
    def __str__(self):
        return self.title
    
# FAQ
class Faq(models.Model):
    quest =models.CharField(max_length=200)
    ans = models.TextField()
    
    def __str__(self):
        return self.quest
    

# Enquiry Model
class Enquiry(models.Model):
    full_name=models.CharField(max_length=150)
    email=models.CharField(max_length=150)
    detail=models.TextField()
    send_time=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'enquiries'
    def __str__(self):
        return self.full_name
    
# Gallery Model
class Gallery(models.Model):
    title=models.CharField(max_length=150)
    detail=models.TextField()
    img=models.ImageField(upload_to="gallery/",null=True)
    
    class Meta:
        verbose_name_plural = 'Galleries'

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe(f"<img src='{self.img.url}' width='80' />")
    

# Gallery Images
class GalleryImage(models.Model):
	gallery=models.ForeignKey(Gallery, on_delete=models.CASCADE,null=True)
	alt_text=models.CharField(max_length=150)
	img=models.ImageField(upload_to="gallery_imgs/",null=True)

	def __str__(self):
		return self.alt_text

	def image_tag(self):
		return mark_safe(f"<img src='{self.img.url}' width='80' />")

# Subscription Plans
class SubPlan(models.Model):
	title=models.CharField(max_length=150)
	price=models.IntegerField()
	max_member=models.IntegerField(null=True)
	highlight_status=models.BooleanField(default=False,null=True)
	validity_days=models.IntegerField(null=True)

	def __str__(self):
		return self.title

# Subscription Plans Features
class SubPlanFeature(models.Model):
	# subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	subplan=models.ManyToManyField(SubPlan)
	title=models.CharField(max_length=150)

	def __str__(self):
		return self.title
    

# Package Discounts
class PlanDiscount(models.Model):
	subplan=models.ForeignKey(SubPlan, on_delete=models.CASCADE,null=True)
	total_months=models.IntegerField()
	total_discount=models.IntegerField()

	def __str__(self):
		return str(self.total_months)

# Subscriber
class Subscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	mobile=models.CharField(max_length=20)
	address=models.TextField()
	img=models.ImageField(upload_to="subs/",null=True)

	def __str__(self):
		return str(self.user)

	def image_tag(self):
		if self.img:
			return mark_safe(f"<img src='{self.img.url}' width='80' />")
		else:
			return 'no-image'

@receiver(post_save, sender=User)
def create_subscriber(sender, instance, created, **kwrargs):
    if created:
        Subscriber.objects.create(user=instance)

# Subscription
class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    plan = models.ForeignKey('SubPlan', on_delete=models.CASCADE, null=True)
    price = models.CharField(max_length=50)  # Consider using DecimalField for monetary values
    reg_date = models.DateField(auto_now_add=True, null=True)
    # end_date should be automatically calculated based on reg_date and plan validity
    # end_date = models.DateField(null=True, blank=True)  # Remove this field
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        # Deactivate other active subscriptions for the user
        if self.is_active:
            Subscription.objects.filter(user=self.user, is_active=True).exclude(pk=self.pk).update(is_active=False)
        super().save(*args, **kwargs)

    @property
    def end_date(self):
        # Calculate end_date based on reg_date and plan validity_days
        if self.reg_date and self.plan:
            return self.reg_date + timedelta(days=self.plan.validity_days)
        return None

    @property
    def is_expired(self):
        # Check if subscription is expired based on current date and end_date
        return timezone.now().date() > self.end_date if self.end_date else False

    def __str__(self):
        return f"{self.user.username} - {self.plan.title}"

    class Meta:
        verbose_name = "Subscription"
        verbose_name_plural = "Subscriptions"
# Trainer
class Trainer(models.Model):
	full_name=models.CharField(max_length=100)
	username=models.CharField(max_length=100,null=True)
	pwd=models.CharField(max_length=50,null=True)
	mobile=models.CharField(max_length=100)
	address=models.TextField()
	is_active=models.BooleanField(default=False)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers/")
	salary=models.IntegerField(default=0)

	facebook=models.CharField(max_length=200,null=True)
	twitter=models.CharField(max_length=200,null=True)
	pinterest=models.CharField(max_length=200,null=True)
	youtube=models.CharField(max_length=200,null=True)

	def __str__(self):
		return str(self.full_name)

	def image_tag(self):
		if self.img:
			return mark_safe(f"<img src='{self.img.url}' width='80' />")
		else:
			return 'no-image'


# Notifications Json Response Via Ajax
class Notify(models.Model):
	notify_detail=models.TextField()
	read_by_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
	read_by_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,blank=True)

	def __str__(self):
		return str(self.notify_detail)

# Markas Read Notification By User
class NotifUserStatus(models.Model):
	notif=models.ForeignKey(Notify, on_delete=models.CASCADE)
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	status=models.BooleanField(default=False)

	class Meta:
		verbose_name_plural='Notification Status'
  

# Assign Subscriber to Trainer
class AssignSubscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)

	def __str__(self):
		return str(self.user)

# Trainer Achivements
class TrainerAchivement(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	title=models.CharField(max_length=100)
	detail=models.TextField()
	img=models.ImageField(upload_to="trainers_achivements/")

	def __str__(self):
		return str(self.title)

	def image_tag(self):
		if self.img:
			return mark_safe(f"<img src='{self.img.url}' width='80' />")
		else:
			return 'no-image'


# TrainerSalary Model
class TrainerSalary(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	amt=models.IntegerField()
	amt_date=models.DateField()
	remarks=models.TextField(blank=True)

	class Meta:
		verbose_name_plural='Trainer Salary'

	def __str__(self):
		return str(self.trainer.full_name)


# Trainer Notifications
class TrainerNotification(models.Model):
	notif_msg=models.TextField()

	def __str__(self):
		return str(self.notif_msg)

	def save(self,*args,**kwargs):
		super(TrainerNotification, self).save(*args,**kwargs)
		channel_layer=get_channel_layer()
		notif=self.notif_msg
		total=TrainerNotification.objects.all().count()
		# total=TrainerNotification.objects.all().filter(notiftrainerstatus__status=True).count()

		async_to_sync(channel_layer.group_send)(
			'noti_group_name',{
				'type':'send_notification',
				'value':json.dumps({'notif':notif,'total':total})
			}
		)

# Markas Read Notification By Trainer
class NotifTrainerStatus(models.Model):
	notif=models.ForeignKey(TrainerNotification, on_delete=models.CASCADE)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	status=models.BooleanField(default=False)

	class Meta:
		verbose_name_plural='Trainer Notification Status'

# SubscriberMsg
class TrainerMsg(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True)
	message=models.TextField()

	class Meta:
		verbose_name_plural='Messages For Trainer'
  
# Reports
class TrainerSubscriberReport(models.Model):
	report_for_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,related_name='report_for_trainer')
	report_for_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name='report_for_user')
	report_from_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE,null=True,related_name='report_from_trainer',blank=True)
	report_from_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name='report_from_user',blank=True)
	report_msg=models.TextField()
 
 
class AppSetting(models.Model):
	logo_img=models.ImageField(upload_to='app_logos/')

	def image_tag(self):
		if self.logo_img:
			return mark_safe(f"<img src='{self.logo_img.url}' width='80' />")
		else:
			return 'no-image'

from django.db import models

class EquipmentInventory(models.Model):
  STATUS_CHOICES = (
    ('available', 'Available'),
    ('under_maintenance', 'Under Maintenance'),
    ('unavailable', 'Unavailable'),
  )
  name = models.CharField(max_length=255)

main/templates/all_services.html
{% extends "base.html" %}
{% block content %}
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading">All Services</h1>
        <div class="row">
            {% for service in services %}
                <div class="col-md-4 mb-3 d-flex align-items-stretch">
                    <div class="card">
                        <img src="{{ service.img.url }}"
                             class="card-img-top"
                             width="auto"
                             height="auto"
                             alt="{{ service.title }}" />
                        <div class="card-body d-flex flex-column">
                            <h3 class="card-title">{{ service.title }}</h3>
                            <p class="card-text">{{ service.detail }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock content %}

main/templates/base.html
{% load static %}
<html lang="en-US">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="keywords" content="gym, mughal" />
    <meta name="description" content="A local gym management system" />
    <!-- Bootstrap CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <!-- Bootstrap Icons -->
    <link href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}"
          rel="stylesheet" />
    <!-- Include jquery -->
    <script type="text/javascript" src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <link rel="icon" type="image/png" href="{% static 'imgs/favicon.ico' %}">
    <title>Mughal Gym</title>
  </head>
  <body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          {% load static %}
          <img src="{% static 'imgs/mughal_gym_logo.png' %}"
               alt="logo"
               height="50px"
               width="100px" />
        </a>
        <!-- Change when find-->
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          {% with request.resolver_match.url_name as url_name %}
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link {% if url_name == 'home' %}active{% endif %}"
                   aria-current="page"
                   href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if url_name == 'gallery' %}active{% endif %}"
                   aria-current="page"
                   href="{% url 'gallery' %}">Gallery</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if url_name == 'pricing' %}active{% endif %}"
                   href="{% url 'pricing' %}">Pricing</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link {% if url_name == 'equipment_list' %}active{% endif %}"
                     href="{% url 'equipment_list' %}">Equipments</a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link {% if url_name == 'enquiry' %}active{% endif %}"
                   href="{% url 'contact_page' %}">Contact Us</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                   href="#"
                   id="navbarScrollingDropdown"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">
                  {% if request.user.is_authenticated %}
                    Hi, {{ request.user.username }}
                  {% elif request.session.trainerLogin %}
                    Hi, {{ request.session.name }}
                  {% else %}
                    Account
                  {% endif %}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                  {% if not request.user.is_authenticated %}
                    <!--comment-->
                    {% if request.session.trainerLogin %}
                      <li>
                        <a class="dropdown-item" href="{% url 'trainer_dashboard' %}">Dashboard</a>
                      </li>
                      <li>
                        <a class="dropdown-item" href="{% url 'trainerlogout' %}">Logout</a>
                      </li>
                    {% else %}
                    <li>
                      <a class="dropdown-item" href="{% url 'signup' %}">Register</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'trainerlogin' %}">Trainer Login</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'admin:index' %}.">Admin Login</a>
                    </li>
                    {% endif %}
                  {% else %}
                    <li>
                      <a class="dropdown-item" href="{% url 'user_dashboard' %}">Dashboard</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'update_profile' %}">Profile</a>
                    </li>
                    <li>
                      <!-- Django 4.1 only supports POST for logout. -->
                      <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="dropdown-item">Logout</button>
                      </form>
                    </li>
                  {% endif %}
                </ul>
              </li>
            </ul>
          {% endwith %}
        </div>
      </div>
    </nav>
    <!-- Header End -->
    <!-- Messages Section -->
    {% if messages %}
      <div class="container mt-3">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} d-flex justify-content-between">
            {{ message }}
            <button class="border-0 bg-transparent close"
                    data-dismiss="alert"
                    aria-label="Close">
              <span aria-hidden="true">×</span> <!-- Using the actual multiplication sign character instead of &times; -->
            </button>
          </div>
        {% endfor %}
      </div>
    {% endif %}
    <!--end messages-->
    {% block content %}
    {% endblock content %}
    <!-- Footer Start -->
    <footer class="container py-5">
      <p class="float-end mb-5">
        <a class="btn btn-outline-success text-black" href="#">Back to top</a>
      </p>
      <p>
        <a class="btn btn-outline-secondary" href="{% url 'pagedetail' 2 %}">Privacy</a>
        <a class="btn btn-outline-secondary" href="{% url 'pagedetail' 3 %}">Terms</a>
        <a class="btn btn-outline-secondary" href="{% url 'faq' %}">FAQ</a>
        <a class="btn btn-outline-secondary" href="{% url 'contact_page' %}">Contact Us</a>
      </p>
      <p class="text-align-center">© 2024 Copyright: MUGHAL FITNESS LEVELS GYM®</p>
    </footer>
    <!-- Bootstrap Bundle -->
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'popper.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

main/templates/contact_us.html
{% extends "base.html" %}
{% block content %}
  <!-- Main Start -->
  <main>
    <!-- Services -->
    <section class="container my-4">
      <h1 class="text-center mb-4 section-heading border-bottom pb-2">Contact Us</h1>
      <div class="row">
        <div class="col-md-6">
          <!--Form Here-->
          <form method="post" action="{% url 'contact_page' %}">
            {% csrf_token %}
            <!-- Email input -->
            <div class="form-outline mb-2">
              {{ form.full_name.errors }}
              <label class="form-label" for="form3Example3">Full Name</label>
              {{ form.full_name }}
            </div>
            <!-- Password input -->
            <div class="form-outline mb-2">
              <label class="form-label" for="form3Example4">Email</label>
              {{ form.email }}
            </div>
            <div class="form-outline mb-2">
              <label class="form-label" for="form3Example5">Detail</label>
              {{ form.detail }}
            </div>
            {% if form.non_field_errors %}
              <div>
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ error }}
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="alert"
                            aria-label="Close"></button>
                  </div>
                {% endfor %}
              </div>
            {% endif %}
            <div class="text-center text-lg-start pt-2">
              <button class="btn btn-primary w-100" type="submit">Submit</button>
            </div>
          </form>
          <table class="table table-bordered">
            <tr>
              <th>Address</th>
              <td>
                42P8+6F7, Qila Didar Singh Bypass, Mohallah Toheed Pura Qila Didar
                Singh, Gujranwala, Punjab 52250, Pakistan
              </td>
            </tr>
            <tr>
              <th>Mobile</th>
              <td>+1 123456799</td>
            </tr>
            <tr>
              <th>Email</th>
              <td>mughalgym@gmail.com</td>
            </tr>
          </table>
        </div>
        <div class="col-md-6">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6757.06268121696!2d74.01278365381145!3d32.135956887311345!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x391f321b1246d97f%3A0xf444f374c94ff5cd!2sMughal%20Gym%20%26%20Fitness%20Centre!5e0!3m2!1sen!2s!4v1707383046213!5m2!1sen!2s"
                  width="600"
                  height="450"
                  style="border: 0"
                  allowfullscreen=""
                  loading="lazy"
                  referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
      </div>
    </section>
    <!-- End -->
  </main>
  <!-- End -->
{% endblock content %}

main/templates/faq.html
{% extends "base.html" %}
{% block content %}
  <!-- Main Start -->
  <main>
    <!-- Services -->
    <section class="container my-4">
      <h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
      <div class="accordion" id="accordionExample">
        {% for faq in faqs %}
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button"
                      type="button"
                      data-bs-toggle="collapse"
                      data-bs-target="#collapseOne{{ forloop.counter }}"
                      aria-expanded="true"
                      aria-controls="collapseOne">{{ faq.quest }}</button>
            </h2>
            <div id="collapseOne{{ forloop.counter }}"
                 class="accordion-collapse collapse"
                 aria-labelledby="headingOne"
                 data-bs-parent="#accordionExample">
              <div class="accordion-body">{{ faq.ans }}</div>
            </div>
          </div>
        {% endfor %}
      </div>
    </section>
    <!-- End -->
  </main>
  <!-- End -->
{% endblock content %}

main/templates/orderemail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Order Email</title>
  </head>
  <body>
    <h3>{{ title }}</h3>
  </body>
</html>

main/templates/pricing.html
{% extends "base.html" %}
{% load static %}
{% load check_package %}
{% load mathfilters %}
{% block content %}
  <link rel="stylesheet"
        type="text/css"
        href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" />
  <main>
    <section class="container my-4">
      <h1 class="text-center mb-4 border-bottom section-heading">Plans</h1>
      <div class="row">
        {% for plan in plans %}
          <div class="col-md-4 mb-3 d-flex align-items-stretch justify-content-around">
            <div class="card {% if plan.highlight_status %}border-primary{% endif %} plan-min-width">
              <!--Card Header-->
              {% if plan.highlight_status %}
                <div class="card-header py-3 text-white bg-primary border-primary">
                  <h4 class="my-0 fw-normal">{{ plan.title }}</h4>
                </div>
              {% else %}
                <div class="card-header py-3">
                  <h4 class="my-0 fw-normal">{{ plan.title }}</h4>
                </div>
              {% endif %}
              <!--Card Body-->
              <div class="card-body d-flex flex-column">
                <!--h1 p an ul -->
                <h3 class="card-title">{{ service.title }}</h3>
                <p class="card-text">{{ service.detail }}</p>
                <h1 class="card-title">
                  ${{ plan.price }}
                  <small class="text-muted fw-light">/{{ plan.validity_days }} Days</small>
                </h1>
                <p class="text-success">Member Capacity {{ plan.max_member|sub:plan.total_members }}</p>
                <ul class="list-unstyled mt-3 mb-4">
                  {% for feature in plan.subplanfeature_set.all %}<li>{{ feature.title }}</li>{% endfor %}
                </ul>
                <!--h1 p and ul end -->
                <!--Button Logic-->
                {% if request.user.is_authenticated %}
                  {% check_user_package request.user.id plan.id as check_pckg %}
                  {% check_pckg_validity request.user.id plan.id as check_valid %}
                  {% if check_pckg %}
                    {% if check_valid %}
                      <a href="{% url 'checkout' plan.id %}"
                         class="btn btn-lg btn-outline-primary mt-auto">Get started</a>
                    {% else %}
                      <a href="#" class="btn btn-lg btn-dark disabled mt-auto">Purchased</a>
                    {% endif %}
                  {% else %}
                    <a href="{% url 'checkout' plan.id %}"
                       class="btn btn-lg btn-outline-primary mt-auto mt-auto">Get started</a>
                  {% endif %}
                {% else %}
                  <a href="{% url 'login' %}"
                     class="btn btn-lg btn-outline-primary mt-auto">Get started</a>
                {% endif %}
                <!--Button Logic End-->
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </section>
    <!--Plans Table View-->
    <section class="container my-4">
      <h2 class="display-6 text-center mb-4">Compare plans</h2>
      <div class="table-responsive">
        <table class="table text-center">
          <thead>
            <tr>
              <th class="plans-th-out"></th>
              {% for plan in plans %}<th class="plans-th-in">{{ plan.title }}</th>{% endfor %}
            </tr>
          </thead>
          <tbody>
            {% for feature in dfeatures %}
              <tr>
                <th scope="row" class="text-start">{{ feature.title }}</th>
                {% for plan in plans %}
                  <td>
                    {% if plan in feature.subplan.all %}
                      <i class="bi bi-check-lg"></i>
                    {% else %}
                      <i class="bi bi-x-lg text-danger"></i>
                    {% endif %}
                  </td>
                {% endfor %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </section>
  </main>
  <script>
    {% comment %} function showLoginMessage() {
        alert('Please login to get started.');
        return false; // Prevent the link from being followed
    }
</script>
  {% endcomment %}
{% endblock content %}